openapi: 3.0.3
info:
  title: Individual Benefits
  description: |
    # Individual benefits data availability
    
    Data is only available for taxpayers who are registered for Self Assessment and reported benefits in the given tax year.
    
    Also, data is only available once PAYE reconciliation has completed. This is the process that determines whether the individual has paid the right amount of tax and, for PAYE-only taxpayers, results in a P800 in the event of [overpayment or underpayment.](https://www.gov.uk/tax-overpayments-and-underpayments)
    
    Reconciliation starts on or around 6th June and runs for around one million individuals per working night. It has usually completed by the end of November. Unfortunately it is not possible to know when reconciliation will be complete for a specific individual.
    
    If we are expecting a P11D, reconciliation will not start for that individual until we have received and processed the P11D. If we receive a P11D unexpectedly, we will re-run the reconciliation.
    
    Data is no longer available once we have received and processed the corresponding Self Assessment return.
    
    # Child Benefit data availability
    
    Data is only available for taxpayers who are entitled to Child Benefit.

    Only data that relates to the current tax year can be requested. The data is likely to be available from mid-May until the Self Assessment filing deadline at the end of January.
 
    **Note:**  While it is possible to pass a tax year to the API, it must represent the current filing tax year. If any other year is passed, HTTP status code 404 will be returned, and the response body will contain the code `NOT_FOUND`. This response will also be returned if the request is made outside of the data availability window.
    
    In cases where data is not available (such as an early or late filing) or where another tax year is being filed, a manual process must be used to calculate and populate any Child Benefit entitlement.
    
    # Authorisation
    
    The endpoints in this API are [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints).
    Your users must grant authority for your software to access them by signing in to their HMRC online account.
    
    The API supports individual and agent users. Note that:
    - Individual users can only access their own information.
    - Agent users can only access their own clients’ data.
    
    The following options are supported for agents:
    
    **Option 1: Agent services account**
    
    If the agent uses an [agent services account](https://www.gov.uk/government/collections/hmrc-online-services-for-agents#agent-services-account), they can access their [existing 64-8 clients](https://www.gov.uk/guidance/how-to-get-authorised-to-act-as-a-tax-agent-on-behalf-of-your-clients#get-authorised-using-online-services-online-forms-or-paper-forms) who they have linked to their agent services account (restricted to 2 years’ history).
    
    **Option 2: HMRC online services for agents account**
    
    If the agent uses an [HMRC online services for agents account](https://www.gov.uk/government/collections/hmrc-online-services-for-agents#hmrc-online-services-for-agents-account) which is enrolled for [Self Assessment for Agents](https://www.gov.uk/guidance/self-assessment-for-agents-online-service), they will be able to access their [existing 64-8 clients](https://www.gov.uk/guidance/how-to-get-authorised-to-act-as-a-tax-agent-on-behalf-of-your-clients#get-authorised-using-online-services-online-forms-or-paper-forms) (restricted to 2 years’ history).
  version: '2.0'
servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production
paths:
  /individual-benefits/sa/{utr}/annual-summary/{taxYear}:
    get:
      tags:
        - individual-benefits
      summary: Get benefits summary
      description: Fetches an individual’s annual benefits summary for the given tax year.
      operationId: getBenefitsSummary
      parameters:
        - $ref: '#/components/parameters/utr'
        - $ref: '#/components/parameters/taxYear'
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/individualBenefitsSaAnnualSummaryResponse'
              example:
                employments:
                  - employerPayeReference: 123/AB456
                    companyCarsAndVansBenefit: 44
                    fuelForCompanyCarsAndVansBenefit: 99
                    privateMedicalDentalInsurance: 64
                    vouchersCreditCardsExcessMileageAllowance: 80
                    goodsEtcProvidedByEmployer: 125
                    accommodationProvidedByEmployer: 375
                    otherBenefits: 16
                    expensesPaymentsReceived: 415
                  - employerPayeReference: 456/AB456
                    companyCarsAndVansBenefit: 50
                    fuelForCompanyCarsAndVansBenefit: 249
                    privateMedicalDentalInsurance: 75
                    vouchersCreditCardsExcessMileageAllowance: 23
                    goodsEtcProvidedByEmployer: 250
                    accommodationProvidedByEmployer: 275
                    otherBenefits: 87
                    expensesPaymentsReceived: 265
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                invalidUtr:
                  description: Invalid UTR
                  value:
                    code: SA_UTR_INVALID
                    message: The provided SA UTR is invalid
                invalidTaxYear:
                  description: Invalid tax year
                  value:
                    code: TAX_YEAR_INVALID
                    message: The provided Tax Year is invalid
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                unauthorisedUser:
                  description: User not authorised to access data for given UTR
                  value:
                    code: UNAUTHORIZED
                    message: Bearer token is missing or not authorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                unmatchedRecipient:
                  description: Data not available for given UTR and tax year (see the data availability section for more details)
                  value:
                    code: NOT_FOUND
                    message: Resource was not found
      deprecated: false
      security:
        - user-restricted:
            - read:individual-benefits
  /individual-benefits/sa/{utr}/child-benefit-entitlement/annual-summary/{taxYear}:
    get:
      tags:
        - individual-benefits
      summary: Get Child Benefit entitlement
      description: Fetches the total amount of Child Benefit that an individual and their partner are entitled to. The specified `taxYear` must be the current filing year.
      operationId: getChildBenefitEntitlement
      parameters:
        - $ref: '#/components/parameters/utr'
        - $ref: '#/components/parameters/taxYear'
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/childBenefitEntitlementResponse'
              example:
                childBenefitEntitlement: 215.49
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                invalidUtr:
                  description: Invalid UTR
                  value:
                    code: SA_UTR_INVALID
                    message: The provided SA UTR is invalid
                invalidTaxYear:
                  description: Invalid tax year
                  value:
                    code: TAX_YEAR_INVALID
                    message: The provided Tax Year is invalid
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                unauthorisedUser:
                  description: User not authorised to access data for given UTR
                  value:
                    code: UNAUTHORIZED
                    message: Bearer token is missing or not authorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                unmatchedRecipient:
                  description: Data is unavailable. Either an invalid tax year or UTR was specified, the individual is not entitled to Child Benefit, or the request was made outside of the data availability window. See the *Child Benefit data availability* section for more details.
                  value:
                    code: NOT_FOUND
                    message: Resource was not found
      deprecated: false
      security:
        - user-restricted:
            - read:individual-benefits
components:
  parameters:
    utr:
      name: utr
      in: path
      description: The 10 digit self-assessment UTR for the individual.
      required: true
      style: simple
      schema:
        type: string
        example: '2234567890'
    taxYear:
      name: taxYear
      in: path
      description: The tax year for which the Child Benefit amount is being retrieved. This must be the current tax year.
      required: true
      style: simple
      schema:
        pattern: ^[0-9]{4}-[0-9]{2}$
        type: string
        example: 2016-17
    acceptHeader:
      name: Accept
      in: header
      style: simple
      description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
      schema:
        type: string
        enum:
          - application/vnd.hmrc.2.0+json
      required: true
    authorizationHeader:
      name: Authorization
      in: header
      style: simple
      description: An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/user-restricted-endpoints) with the `read:individual-benefits` scope.
      schema:
        type: string
        example: Bearer bb7fed3fe10dd235a2ccda3d50fb
      required: true
  securitySchemes:
    user-restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) API requests using an OAuth 2.0 Bearer Token in the Authorization header.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:individual-benefits: Access personal and employment-based benefits information
  schemas:
    errorResponse:
      title: errorResponse
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
          description: The error code
        message:
          type: string
          description: The error message
    employment:
      title: employment
      required:
        - employerPayeReference
      type: object
      properties:
        employerPayeReference:
          type: string
          description: The employer’s PAYE reference.
          example: 123/AB456
        companyCarsAndVansBenefit:
          type: number
          description: The total value of company cars and vans.
          example: 44
        fuelForCompanyCarsAndVansBenefit:
          type: number
          description: The total value of fuel for company cars and vans.
          example: 99
        privateMedicalDentalInsurance:
          type: number
          description: The total value of private medical and dental treatment and insurance.
          example: 64
        vouchersCreditCardsExcessMileageAllowance:
          type: number
          description: The value of benefits in the form of vouchers, credit cards and excess mileage allowance.
          example: 80
        goodsEtcProvidedByEmployer:
          type: number
          description: The total value of goods and other assets provided by the employer.
          example: 125
        accommodationProvidedByEmployer:
          type: number
          description: The total value of accommodation provided by the employer.
          example: 375
        otherBenefits:
          type: number
          description: The total value of other benefits, including interest-free loans and loans below the HMRC official rates.
          example: 16
        expensesPaymentsReceived:
          type: number
          description: The value of expenses payments received and balancing charges.
          example: 415
    individualBenefitsSaAnnualSummaryResponse:
      title: individualBenefitsSaAnnualSummaryResponse
      required:
        - employments
      type: object
      properties:
        employments:
          type: array
          items:
            $ref: '#/components/schemas/employment'
          description: An unordered list of one or more employments for which the taxpayer reported any benefits for the given tax year.
      description: Individual benefits summary
    childBenefitEntitlementResponse:
      type: object
      required:
        - childBenefitEntitlement
      properties:
        childBenefitEntitlement:
          type: number
